name:                scrbl
version:             0.1.0.0
github:              "githubuser/scrbl"
license:             BSD3
author:              "Mehrab Hoque"
maintainer:          "mehrabhoque@gmail.com"
copyright:           "2019 Mehrab Hoque"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/utagai/scrbl#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring
- directory
- filepath
- process

library:
  source-dirs: src

executables:
  scrbl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrbl

tests:
  scrbl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scrbl
    - HUnit
    - directory
